@startuml
' External Systems
node "LINE Platform" as line #LightBlue
database "Google Sheets" as sheets #honeydew

' Google Cloud Project
package "Google Cloud Project" {
    [Cloud Run (Ktor)] as ktor
    [Secret Manager] as secret

    package "Observability" {
        [Cloud Logging] as logging
        [Cloud Monitoring] as monitoring
    }
}

' Main Flow
line -down-> ktor : Webhook
ktor -up-> line : Reply Message

' Confidential Data
ktor -right-> sheets : Fetch Data
ktor -left-> secret : Fetch Keys

' Operation Flow
ktor -down-> logging : Logs
logging -right-> monitoring : Metrics / Alert

@enduml
